### ISSUE TITLE
[Feature Request] Support the standard Lora embedding format <lora:_>

### ISSUE THREAD

**Issue by ArrowM** [NVIDIA/Stable-Diffusion-WebUI-TensorRT#56]
The current Lora selection feels clunky and makes it difficult/impossible to use them with automated workflows. I think it would be a widely appreciated feature to support the standard Lora format for A1111: `some prompt <lora:my_lora:1.0>`

**Comment by MorkTheOrk** [comment]
Hey! This is not easily possible in this extension due to the access we get from automatic1111s webui, we provide a function that runs the Unet inference and is being called by the webui, we dont have control over prompt parsing. Additionally, there is no current way for us to refit the engine with the LoRA directly from the checkpoint.

**Comment by ArrowM** [comment]
Hm, I know extensions can read and modify prompts prior to inference, for example https://github.com/adieyal/sd-dynamic-prompts. Would it not be possible to do something similar in this extension?

**Comment by contentis** [comment]
I'd like to get this working in the future, but I cannot give you an ETA on when this will be possible. As this is a side-project, I need to find time, as this will need work on core components. And especially in these first days it's gonna be bug fixing.
Stay tuned for updates.
